http:
  routers:
    catch-all:
      rule: "HostRegexp(`.+`)"
      priority: 1
      entrypoints:
        - websecure
      middlewares:
        - redirect-to-error
      service: noop
      tls:
        certResolver: myresolver
        domains:
          - main: "*.citrusdental.in"
            sans:
              - "citrusdental.in"

  middlewares:
    redirect-to-error:
      redirectRegex:
        regex: ".*"
        replacement: "https://error.citrusdental.in"
        permanent: false

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:1"

tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: myresolver
        domain:
          main: "*.citrusdental.in"
          sans:
            - "citrusdental.in"
