entryPoints:
  websecure:
    address: :443
    http3:
      advertisedPort: 443
    asDefault: true
    http:
      tls:
        certResolver: myresolver
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

ping:
  manualRouting: true

providers:
  docker:
    exposedByDefault: false
    network: internal_bridge

api:
  dashboard: true
log:
  level: INFO

certificatesResolvers:
  myresolver:
    acme:
      storage: "/etc/acme/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

