services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - /home/dietpi/localstack/data/vaultwarden_data:/data
    expose:
      - "3012"
    networks:
      - network-layer
    env_file: /home/dietpi/localstack/secrets/ab-vaultwarden.env
    extra_hosts:
      - pg.ab18.in=10.10.10.11
    labels:
      - traefik.enable=true
      - traefik.http.routers.vault.rule=Host(`vault.ab18.in`)
      - traefik.http.routers.vault.middlewares=vault-headers
      - traefik.http.services.vault.loadbalancer.server.port=80
      - traefik.http.middlewares.vault-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.vault-ws.rule=Host(`vault.ab18.in`) && Path(`/notifications/hub`)
      - traefik.http.routers.vault-ws.middlewares=vault-headers
      - traefik.http.services.vault-ws.loadbalancer.server.port=3012
      - homepage.group=Utilities
      - homepage.name=VaultWarden
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/bitwarden.png
      - homepage.href=https://vault.ab18.in
      - homepage.description=Store your secrets securely
      #- traefik.http.routers.vault.middlewares=auth
networks:
  network-layer:
    name: internal_bridge
    external: true
