services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - /home/dietpi/localstack/data/vaultwarden_data:/data
      - ./config/config.json:/data/config.json
    expose:
      - "3012"
    networks:
      - network-layer
    env_file: /home/dietpi/localstack/secrets/ab-vaultwarden.env
    extra_hosts:
      - pg.ab18.in=10.10.10.11
    labels:
      - traefik.enable=true
      - traefik.http.routers.vault.rule=Host(`vault.ab18.in`)
      - traefik.http.routers.vault.middlewares=vault-headers
      - traefik.http.routers.vault.service=vault
      - traefik.http.services.vault.loadbalancer.server.port=80
      - traefik.http.middlewares.vault-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.vault-ws.rule=Host(`vault.ab18.in`) && Path(`/notifications/hub`)
      - traefik.http.routers.vault-ws.middlewares=vault-headers
      - traefik.http.routers.vault-ws.service=vault-ws
      - traefik.http.services.vault-ws.loadbalancer.server.port=3012
      #- traefik.http.routers.vault.middlewares=auth
networks:
  network-layer:
    name: internal_bridge
    external: true
