---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: ab18 - Home
headerStyle: boxed
quicklaunch:
  provider: google
  searchDescriptions: true
  showSearchSuggestions: true
disableIndexing: true
pwa:
  icons:
    - src: https://github.com/surajverma/homehub/blob/main/static/icons/icon-192.png
      type: image/png
      sizes: 192x192
    - src: https://github.com/surajverma/homehub/blob/main/static/icons/icon-512.png
      type: image/png
      sizes: 512x512
  shortcuts:
    - name: Local
      url: "/#local" # opens the first tab
    - name: ab18.in
      url: "/#ab18.in" # opens the second tab
    - name: citrusdental.in
      url: "/#citrusdental.in" # opens the third tab
favicon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homehub.png
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  finnhub: d6dtur1r01qm89pkv1p0d6dtur1r01qm89pkv1pg
layout:
  Local Utilities:
      tab: Local
      iconsOnly: true
      style: row
      columns: 3
      header: false
      Local Networks:
        style: row
        columns: 3
  Utilities:
      tab: ab18.in
      iconsOnly: true
      style: row
      columns: 3
      header: false
  CD Utilities:
      tab: citrusdental.in
      iconsOnly: true
      style: row
      columns: 3
      header: false
