version: 2
updates:
  - package-ecosystem: gomod
    directory: /webauthn-proxy
    schedule:
      interval: weekly
    groups:
      webauthn-proxy-go:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /webauthn-proxy
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /home-cli
    schedule:
      interval: weekly
    groups:
      home-cli-go:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns: ["*"]
