services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    networks:
      - internal_bridge
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./config/traefik/acme.json:/etc/acme/acme.json
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
    labels:
      - traefik.enable=true
      - traefik.http.routers.proxy.rule=Host(`proxy.citrusdental.in`)
      - com.centurylinklabs.watchtower.enable=false
      - traefik.http.routers.proxy.service=api@internal
      - homepage.group=CD Utilities
      - homepage.name=Traefik
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/traefik-proxy.png
      - homepage.href=https://proxy.citrusdental.in
      - homepage.description=Traefik Reverse Proxy
      - homepage.widget.type=traefik
      - homepage.widget.url=https://proxy.citrusdental.in
    secrets:
      - cf_dns_api_token

  pihole:
    image: pihole/pihole
    container_name: pihole
    hostname: pihole
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=false
    networks:
      pihole_macvlan:
        ipv4_address: 10.10.10.10
    environment:
      - TZ=Asia/Kolkata
      - FTLCONF_DNS_REVSERVERS=true,10.10.0.0/24,10.10.10.1,lan
      - FTLCONF_DNS_DOMAINNEEDED=true
      - FTLCONF_DNS_BLOCKESNI=false
      - FTLCONF_DNS_EXPANDHOSTS=true
      - FTLCONF_DNS_DNSSEC=true
      - FTLCONF_DNS_SHOWDNSSEC=false
      - FTLCONF_DNS_UPSTREAMS=1.1.1.1
      - WEBPASSWORD_FILE=/run/secrets/pihole_web_password
      - FTLCONF_DATABASE_MAXDBDAYS=3
      - PIHOLE_UID=1000
      - PIHOLE_GID=1000
      - FTLCONF_WEBSERVER_PORT=80
    cap_add:
      - CAP_SYS_NICE
      - CAP_SYS_TIME
      - NET_ADMIN
    volumes:
      - ./config/pihole:/etc/pihole
    secrets:
      - pihole_web_password

networks:
  internal_bridge:
    name: internal_bridge
    external: true
  pihole_macvlan:
    name: pihole_macvlan
    external: true

secrets:
  cf_dns_api_token:
    file: /home/dietpi/localstack/secrets/cf_dns_api_token
  pihole_web_password:
    file: /home/dietpi/localstack/secrets/pihole_web_password
