services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - SELKIES_MANUAL_WIDTH=1366
      - SELKIES_MANUAL_HEIGHT=768
      - SELKIES_USE_BROWSER_CURSORS=True
      - SELKIES_AUDIO_ENABLED=False
      - SELKIES_MICROPHONE_ENABLED=False
      - SELKIES_UI_SIDEBAR_SHOW_GAMING_MODE=False
      - SELKIES_GAMEPAD_ENABLED=False
      # - CUSTOM_USER=ab18
      # - PASSWORD=CuF4vruPK4PQxU5
    volumes:
      - /home/dietpi/localstack/config/firefox:/config
    shm_size: 512m
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.remote.rule=Host(`remote.ab18.in`)
      - traefik.http.routers.remote.middlewares=auth
      - homepage.group=Utilities
      - homepage.name=FireFox
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/firefox.png
      - homepage.href=https://remote.ab18.in
      - homepage.description=FireFox Browser
    networks:
      - network-layer
networks:
  network-layer:
    name: tailscale_bridge
    external: true