services:
  esphome:
    image: esphome/esphome
    container_name: esphome
    restart: always
    networks:
      - network-layer
    volumes:
      - ./config/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    env_file: /home/dietpi/localstack/secrets/ab-homeautomation.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.esphome.rule=Host(`esphome.ab18.in`)
      - traefik.http.routers.esphome.middlewares=auth
networks:
  network-layer:
    name: internal_bridge
    external: true
