services:
  esphome:
    image: esphome/esphome
    container_name: esphome
    restart: always
    networks:
      - network-layer
    volumes:
      - ./config/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    env_file: /home/dietpi/localstack/secrets/ab-homeautomation.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.esphome.rule=Host(`esphome.ab18.in`)
      - traefik.http.routers.esphome.middlewares=auth
      - homepage.group=Local Utilities
      - homepage.name=ESPHome
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/esphome-alt-light.png
      - homepage.href=https://esphome.ab18.in
      - homepage.description=Control ESPHome Devices
networks:
  network-layer:
    name: tailscale_bridge
    external: true
