services:
  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    restart: always
    # Setup the server that provides the web gui
    entrypoint:
      - sh
      - -c
      - |
        exec kopia server start \
          --disable-csrf-token-checks \
          --insecure \
          --address=0.0.0.0:51515 \
          --server-username="$$KOPIA_SERVER_USERNAME" \
          --server-password="$$KOPIA_SERVER_PASSWORD"
    volumes:
      - /home/dietpi/localstack/data/kopia/config:/app/config
      - /home/dietpi/localstack/data/kopia/cache:/app/cache
      - /home/dietpi/localstack/data/kopia/logs:/app/logs
      - /home/dietpi/localstack/data/kopia/rclone:/app/rclone
      - /home/dietpi/localstack:/data-ab:ro
      - nfs-data:/data-cd:ro
      - /home/dietpi/localstack/data/kopia/repository:/repository
      - /home/dietpi/localstack/data/kopia/tmp:/tmp:shared
    labels:
      - traefik.enable=true
      - traefik.http.routers.kopia.rule=Host(`backup.ab18.in`)
      - traefik.http.services.kopia.loadbalancer.server.port=51515
      - traefik.http.routers.kopia.middlewares=auth
    networks:
      - network-layer
    env_file: /home/dietpi/localstack/secrets/ab-kopia.env
networks:
  network-layer:
    name: internal_bridge
    external: true
volumes:
  nfs-data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.10.10.12,rw,nolock,soft
      device: :/home/dietpi/localstack