services:
  kopia:
    build: .
    container_name: kopia
    restart: always
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --without-password
      - --allow-extremely-dangerous-unauthenticated-server-on-the-network
      - --enable-actions
    volumes:
      - /home/dietpi/localstack/data/kopia/config:/app/config
      - /home/dietpi/localstack/data/kopia/cache:/app/cache
      - /home/dietpi/localstack/data/kopia/logs:/app/logs
      - /home/dietpi/localstack/data/kopia/rclone:/app/rclone
      - /home/dietpi/localstack:/data-ab
      - /home/dietpi/localstack/data/kopia/tmp:/tmp:shared
      - ./scripts/pre-snapshot.sh:/scripts/pre-snapshot.sh:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.kopia.rule=Host(`backup.ab18.in`)
      - traefik.http.services.kopia.loadbalancer.server.port=51515
      - traefik.http.routers.kopia.middlewares=auth
    networks:
      - network-layer
    env_file: /home/dietpi/localstack/secrets/ab-kopia.env

networks:
  network-layer:
    name: internal_bridge
    external: true
