services:
  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    restart: always
    # Setup the server that provides the web gui
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --without-password
      #- --server-username=admin
      #- --server-password=admin
    volumes:
      # Mount local folders needed by kopia
      - ${KOPIA_DATADIR}/config:/app/config
      - ${KOPIA_DATADIR}/cache:/app/cache
      - ${KOPIA_DATADIR}/logs:/app/logs
      - ${KOPIA_DATADIR}/rclone:/app/rclone
      # Mount local folders to snapshot
      - /home/dietpi/localstack:/data-ab:ro
      - nfs-data:/data-cd:ro
      # Mount repository location
      - /${KOPIA_DATADIR}/repository:/repository
      # Mount path for browsing mounted snapshots
      - ${KOPIA_DATADIR}/tmp:/tmp:shared
    labels:
      - traefik.enable=true
      - traefik.http.routers.kopia.rule=Host(`backup.ab18.in`)
      - traefik.http.services.kopia.loadbalancer.server.port=51515
      - traefik.http.routers.kopia.middlewares=auth
      - homepage.group=Local Utilities
      - homepage.name=Kopia
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/kopia.png
      - homepage.href=https://backup.ab18.in
      - homepage.description=Backup System
    networks:
      - network-layer
    env_file: .env
networks:
  network-layer:
    name: tailscale_bridge
    external: true
volumes:
  nfs-data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.10.10.12,rw,nolock,soft
      device: :/home/dietpi/localstack