services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    networks:
      - network-layer
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser.rule=Host(`files.citrusdental.in`)
      # - homepage.group=Local Utilities
      # - homepage.name=File Browser
      # - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/filebrowser-quantum.png
      # - homepage.href=https://files.ab18.in
      # - homepage.description=File Manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - FB_NOAUTH=true
      # - FB_AUTH_HEADER=X-Auth-Request-User
      # - FB_AUTH_METHOD=proxy
    volumes:
      # This exposes your localstack directory to the app
      - /home/dietpi/citrusdental:/srv
      # Data persistence for FileBrowser settings/users
      - /home/dietpi/localstack/data/filebrowser_data:/database
      - /home/dietpi/localstack/config/filebrowser:/config

networks:
  network-layer:
    name: tailscale_bridge
    external: true
