services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    restart: always
    env_file: /home/dietpi/localstack/secrets/ab-localstack.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.enable=false
  # otel:
  #   image: grafana/otel-lgtm:latest
  #   container_name: otel
  #   volumes:
  #     - /home/dietpi/localstack/data/otel_data:/data
  #   restart: always
  #   networks:
  #     - network-layer
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.otel.rule=Host(`otel.ab18.in`)
  #     - traefik.http.services.otel.loadbalancer.server.port=3000
networks:
  network-layer:
    name: internal_bridge
    external: true
