services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: sync.ab18.in
    networks:
      - network-layer
    restart: always
    env_file: /home/dietpi/localstack/secrets/ab-syncthing.env
    volumes:
      - ./config:/config
      - /home/dietpi/localstack/secrets/syncthing:/secrets:ro
      - ./init/symlink-secrets.sh:/custom-cont-init.d/01-symlink-secrets.sh:ro
      - /home/dietpi/music:/music
      - /home/dietpi/movies:/movies
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncthing.rule=Host(`sync.ab18.in`)
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
      - traefik.tcp.routers.syncthing.rule=HostSNI(`sync.ab18.in`)
      - traefik.tcp.routers.syncthing.entrypoints=websecure
      - traefik.tcp.routers.syncthing.tls=true
      - traefik.tcp.services.syncthing_tcp.loadbalancer.server.port=22000
#      - traefik.http.routers.syncthing.middlewares=auth
networks:
  network-layer:
    name: internal_bridge
    external: true