services:
  rustpad:
    image: ekzhang/rustpad
    container_name: rustpad
    restart: always
    networks:
      - network-layer
    labels:
      - traefik.enable=true
      - traefik.http.routers.pad.rule=Host(`pad.ab18.in`)
      - traefik.http.services.pad.loadbalancer.server.port=3030
      - traefik.http.routers.pad.service=pad
    env_file: /home/dietpi/localstack/secrets/ab-rustpad.env
    volumes:
      - /home/dietpi/localstack/data/rustpad_data:/data
networks:
  network-layer:
    name: internal_bridge
    external: true