services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: always
    stdin_open: true
    healthcheck:
      disable: true
    env_file: /home/dietpi/localstack/secrets/ab-excalidraw.env
    networks:
      - network-layer
    labels:
      - traefik.enable=true
      - traefik.http.routers.draw.rule=Host(`draw.ab18.in`)
      - traefik.http.routers.draw.middlewares=auth
networks:
  network-layer:
    name: internal_bridge
    external: true