services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_UPDATE_ON_START=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=abcde
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - internal_bridge
    labels:
      - traefik.enable=true
      - traefik.http.routers.watchtower.rule=Host(`watchtower.citrusdental.in`)
      - traefik.http.services.watchtower.loadbalancer.port=8080
      - homepage.group=CD Utilities
      - homepage.name=Watch Tower
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/watchtower.png
      - homepage.description=Watch Tower for Image Updates
      - homepage.widget.type=watchtower
      - homepage.widget.url=https://watchtower.citrusdental.in
networks:
  internal_bridge:
    external: true
