services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_UPDATE_ON_START=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=abcde
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - internal_bridge
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - traefik.enable=true
      - traefik.http.routers.watchtower.rule=Host(`watchtower.citrusdental.in`)
      - traefik.http.services.watchtower.loadbalancer.port=8080
networks:
  internal_bridge:
    external: true
