services:
  stirlingpdf:
    image: stirlingtools/stirling-pdf:latest-ultra-lite
    container_name: stirlingpdf
    networks:
      - network-layer
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.pdf.rule=Host(`pdf.ab18.in`)
      - traefik.http.routers.pdf.middlewares=auth
networks:
  network-layer:
    name: internal_bridge
    external: true